apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: vle-lesson
spec:
  template:
    metadata:
      labels:
        app: vle-lesson
    spec:
      containers:
      - image: ottermad/vle-lesson:latest
        name: vle-lesson
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DATABASE
          value: user_db
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
        ports:
        - containerPort: 80
